shell = 'zsh'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
apply = ['defer']

